### ISSUE TITLE
Spacing in YAML - SublimeText

### ISSUE THREAD

**Issue by dbdennis** [ZettelGeist/zettelgeist#1]
One more thing to check [along way….] :  Sublime Text wants to make all Tabs 2 spaces in YAML files.  Will that work?  

I set it globally for Sublime Text to be 1 space, but it reads YAML files specifically and adjusts… One could put in special YAML override, but that’s getting very program specific.  [Which I assume we want to avoid.]

[2:57] 
Another minor thing.  Besides the colons issue, above.  Should there be a space before hyphens under tags: or mentions: or cite:?  

As in:

cite:
 - Castells Network 2016
 - 65

Sometimes the YAML Linter made me change that, most times not.  See if you are able to get Bibtex to work as is…

**Comment by gkthiruvathukal** [comment]
Dave, I believe we addressed both of these issues on Slack. One comment: to make sure we can triage issues properly, please report only one issue when using GitHub's issue tracker.

I believe Sublime Text is just making this decision arbitrarily. As far as I can tell, YAML has flexibility when it comes to the number of spaces, as long as it's consistent.

Regarding spacing for lists, I believe it is a matter of being consistent in terms of number of spaces as well.
