### ISSUE TITLE
Add support for outlining

### ISSUE THREAD

**Issue by gkthiruvathukal** [ZettelGeist/zettelgeist#18]
The whole idea of creating  ZettelGeist in the first place was to assist in the production of _scholarly_ and _research_ works.  Of course, it can be used for everything. However, we feel that most other (unnamed) notetaking systems reach an audience that is not looking for what we offer, especially with their WYSIWYG focus. 

We want the ability to associate a zettel with a section of an outline structure. The ability to noodle with a structure and suggest where a zettel might help to support the argument is a key aspect of producing a scholarly work. As @dbdennis and I discussed in a private chat, some works have been produced almost entirely from zettels (index cards).

My current thought is to be extremely lightweight. We will have an `outline` field (a very special field) that supports mapping a zettel to a work and any section/subsection/... within the work.

Suppose you are writing a book (Book Title) and an essay (Essay Title), you could suggest a *placement* a zettel as follows:

```
outline:
- Book Title
  - Heading A
    - Subheading A2

- Essay Title
   - Opening
```

This would allow for generating a document from `zfind` that maps the resulting zettels to the appropriate sections of an outline. It must be noted that this is not fully round trip but opens the door for a full _noodling_ system where you could get most of a paper or book from an existing collection of zettels. This would allow us to mimic the `\input` concept of LaTeX but not ever have to explicitly input anything.

@gkthiruvathukal  would like to prototype the idea and see whether this can allow us to generate most (or all) of an essay/document from a more modular structure. This would also allow for instant preview, which would help our immediate project (our history book).

**Comment by gkthiruvathukal** [comment]
Just a follow up, this has some implications.

Unlike our string and list fields, we are going to need a more tree-structured representation.  The proposed syntax above is, at best, preliiminary.

Another possible syntax might be:

```
works:
  -  title: "Book Title"
     outline:
     - Heading A
     - Subheading A2
  - title: "Essay Title"
    outline:
    - Heading X
    - Subheading X5
      - Subsubheading X51
```

There will be no limits on how many works can be described.
There will also be no limits  on sectioning structure.

Another syntax I am considering:

works:
   - title: "Book Title"
     outline: ["Heading A", "Subheading A2"]
```

**Comment by gkthiruvathukal** [comment]
@dbdennis and @icornelius, I would like your input. The only thing between me and coding it is knowing that the two of you do not think I am crazy. (Well, I mean, when it comes to this idea.)

**Comment by icornelius** [comment]
Three thoughts.

1. I'd like the option of associating zetteln with a project and project-part.
2. I'd like the option of generating ordered output from `zfind`. We're talking about mapping a set of zetteln to a project-structure. I see the value of that, but I want to raise a more general question about ordered query results. Sometimes I want to see all zetteln from a given source, sorted by page-value -- i.e., displayed in the order of appearance in the book on which I have taken notes.
3. The move from yaml to markdown expands the versatility of ZettelGeist but will require careful thinking about the content of the `document` element. In my zetteln, the `note` element (migrated to `document` in the latest version of ZettelGeist) is always and only a verbatim quotation from a source; the source is identified by Better BibTeX citation key and page reference in the `cite` element. My own writing has gone in the `comment` element. This is the right disposition of content for note-taking, but the current expansion of the scope of ZettelGeist changes things. If I am using ZettelGeist to write modular components of an article, I want to use the `document` element for my own writing, since that is the markdown-formatted element. I'll then have some zetteln in which the `document` element is a quotation from a source and others in which the `document` element is my own prose. I'll need to keep those separate.

**Comment by gkthiruvathukal** [comment]
@icornelius This is helpful input. 

To comment on each of the above:

1. I think this is something worthy of consideration. You can do this with `tags:` now by making a unique project "tag". If you wanted to have project and project part, you could make two tags. These can then be used in an and (&) query in `zfind`. But I do think we could consider additional fields for this.

2. This is actually possible now, because when you use `zfind` with the `--fileset` option, you can pathnames in lexicographic order. However, I have also be contemplating a `--sort-by` option. 

3. I think your point is valid, but I would like to stress that `document` is the new `note`. The key thing to understand is that--all along--David and I did intend `note` to be (as you would see it on an index card) the *details* of the card.  `comment` is primarily intended for a "note to self" and `summary` is your *scholarly* summary of whatever is in the `note`/`document`.

Having said all of this, ultimately, the idea of ZettelGeist is to have a concise set of fields.  Just so you know, in one scenario, we could keep `note` around (as is) and use `document` for when you want to use a zettel for drafting in more detail. We have not deleted the `note` field, so if you wanted, you could continue using this for your notes, and we can just convert them to Markdown without any actual content in the document (yet).

Let me know if this sounds satisfactory. In the end, little harm is done about supporting our existing uses/users, and if you want to convert the YAML files to MD without going entirely to MD, this is a workflow we can support.

For me and @dbdennis, we needed `document` because we want to stay "within the system" to do as much writing as possible. However, even in our case, we're likely to have a bunch of smaller zetteln. 

Sometimes I think we should have had a `quote` field for situations where we we want to quote a text verbatim. The rest would be about analysis. For now, I think you can use `note` for this purpose and `document` if you need to write a more lengthy analysis (draft paragraph). 

I'm taking away from this follow up that we need to *suggest* a usage for `comment` (kind of like a to-do), `summary` (terse scholarly observation), `note` (the actual text being cited), and `document` (draft words intended for a larger work). Depending on the researcher, `note` and `document` can be used somewhat interchangeably--or not at all!

**Comment by icornelius** [comment]
@gkthiruvathukal thanks for discussion. I recognize that I am moving us off-topic. I'll open new issues about `note`/`document` and sorted output from `zfind`. 
To return to outlining. What I meant to say in (1) is that a zettel-to-project association seems to be entailed in the proposed outline-module and has wider application. Even if I do not (yet) have use for outlining functionality, I may want to associate zetteln with a project. Your `works` syntax allows for this and allows for incremental refinements to the project-zettel association (headings, subheadings, etc.) as my understanding of my project develops. I *could* use tags to make the initial zettel-to-project association, but the `works` syntax (a) enables ordered output from `zfind` and (b) permits me to keep `tags` for content-based keywords. I like this.

**Comment by gkthiruvathukal** [comment]
@icornelius Based on your excellent follow up, I think we're going to start with a lighter-weight system for outlining. I'm going to make a separate proposal about this (as an issue) and close out this one after doing so.

**Comment by gkthiruvathukal** [comment]
Marking this as resolved. The ZettelGeist tutorial example shows how to create an outline and *fill it in* using `zfind` queries.
