### ISSUE TITLE
remove zcreate

### ISSUE THREAD

**Issue by gkthiruvathukal** [ZettelGeist/zettelgeist#19]
I recently introduced changes to `zimport` to craete the database from scratch, whether present or not. Our user base is still relatively small, but I'd like to make sure everyone is ok with this before removing it formally.

**Comment by icornelius** [comment]
Yes, I think the `--create` option is an improvement.

**Comment by gkthiruvathukal** [comment]
@icornelius Thanks for the follow up. I'm going to put this on the list of things to remove in the next major release. For now, I think there is little harm to keeping it, but most people are probably going to appreciate `zimport --create` as an all-in-one process.

**Comment by gkthiruvathukal** [comment]
Going to close this one out. Even though we don't need it, some existing workflows may depend on it. It's a relatively small inconvenience to continue maintaining it.
