### ISSUE TITLE
broken link "Installation"

### ISSUE THREAD

**Issue by dwbcampbell** [ZettelGeist/zettelgeist#22]
On this page
https://github.com/ZettelGeist/zettelgeist/wiki/Installing-the-Tools

The "Installation" link does not take you to the installation page but to here: https://github.com/install

**Comment by gkthiruvathukal** [comment]
@dwbcampbell Thanks so much for reporting this issue. I'll get this fixed ASAP.

**Comment by gkthiruvathukal** [comment]
@dwbcampbell There is also one other issue. I have the wrong page title for this. This is our Basic Overview page. Somehow I gave it the wrong title when porting from the web site version.

**Comment by gkthiruvathukal** [comment]
Thank you, @dwbcampbell! 

The page you mentioned is now https://github.com/ZettelGeist/zettelgeist/wiki/Getting-Started.
Within this page, we now point to the correct installation page, https://github.com/ZettelGeist/zettelgeist/wiki/Installing-the-Tools.

I believe it's correct so I am going to mark this as resolved. But please don't hesitate to reopen or submit a new issue if you find any other problems. Thanks for your interest in our project!

**Comment by dwbcampbell** [comment]
Hi @gkthiruvathukal ,

Thanks for fixing this issue. Is there a forum for asking questions or giving feedback? I've been able to use zettelgeist and quite like it.

regards
Douglas
> Thank you, @dwbcampbell!
> 
> The page you mentioned is now https://github.com/ZettelGeist/zettelgeist/wiki/Getting-Started.
> Within this page, we now point to the correct installation page, https://github.com/ZettelGeist/zettelgeist/wiki/Installing-the-Tools.
> 
> I believe it's correct so I am going to mark this as resolved. But please don't hesitate to reopen or submit a new issue if you find any other problems. Thanks for your interest in our project!

**Comment by gkthiruvathukal** [comment]
@dwbcampbell  Thanks for waiting for a response on this query! I just set up GitHub Discussions (see Discussions tab).  Please do post any questions or comments there! We are definitely interested to engage with the community.
