### ISSUE TITLE
--show-filename gives no output

### ISSUE THREAD

**Issue by icornelius** [ZettelGeist/zettelgeist#23]
The `zfind` option `--show-filename` gives no output. The `--count` option and other `--show-KEY` options function as expected.

I am building the database with the command 

```shell
zimport --create --database index.db --dir path/to/zetteln --fullpath
```

**Comment by gkthiruvathukal** [comment]
Thanks for testing this, @icornelius. This is probably related to `filename` and `document` being special (extra) fields. Should be a straightforward issue, I hope.

**Comment by gkthiruvathukal** [comment]
Thanks, @icornelius (and @dbdennis). I will push this fix out shortly.

**Comment by gkthiruvathukal** [comment]
@icornelius This issue is fixed with the recent release of ZettelGeist  that you also have installed. So you should be all set.
