### ISSUE TITLE
"--show-all" option with zfind? 

### ISSUE THREAD

**Issue by avanides** [ZettelGeist/zettelgeist#30]
It would very useful to run a zfind query and have the option to output the results as entire cards, which would in essence recreate the act of taking a physical Zettel out of an actual Zettelkasten. I am often not aware of everything that I wrote down in a given Zettel, much of which is likely of relevance for whatever it is I might be researching. Having the option to "--show-all" (or something similar) instead of listing every possible "--show" would streamline the process significantly.

**Comment by icornelius** [comment]
Thanks for this feature request.

Meantime you can get the results you seek with this command

```
cat $(zfind --database index.db --query-string 'KEY:"VALUE"' --show-filename | grep PATH | sed 's/filename: //')
```

Notes: 

1. Replace KEY and VALUE with your search criteria
2. Replace PATH with any part of the path to your zetteln
3. Optionally, pipe to `less`

To troubleshoot, build up from the core `zfind` command.

**Comment by gkthiruvathukal** [comment]
@avanides and @icornelius, we now have a `--show-all` option.  You'll have to upgrade to the latest version via `pip`.

**Comment by gkthiruvathukal** [comment]
The docs will need to have a corresponding update, @icornelius. The semantics of `--show-all` are to show any field that is actually being used in the zettel.

**Comment by icornelius** [comment]
Docs are updated: https://github.com/ZettelGeist/zettelgeist/wiki/Getting-Started
Thanks @gkthiruvathukal and @avanides !

**Comment by avanides** [comment]
@gkthiruvathukal @icornelius - thanks so much for this - works flawlessly!

**Comment by gkthiruvathukal** [comment]
Happy new year, @avanides!
